version: "3.7"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
    - 5432:5432
  mountebank:
    build:
      context: ./mountebank
      dockerfile: Dockerfile
    ports:
    - 2525:2525
    - 4545:4545
    entrypoint: "npm run mock"
